name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: make
      id: make
      run: make
      continue-on-error: false

  change_status:
    needs: [build]
    uses: ./.github/workflows/transition.yml
    with:
      issue: "IM-1"
    secrets:
      SF_ORG_ALIAS: ${{ secrets.JIRA_BASE_URL }}
      SF_USERNAME: ${{ secrets.JIRA_USER_EMAIL }}
      SF_INSTANCE_URL: ${{ secrets.JIRA_API_TOKEN }}


