name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: make
      id: make
      run: make
      continue-on-error: false

    - id: change_status
      uses: ./.github/workflows/transition.yml
      with:
        issue: "IM-1"
        
