name: Change status

on: 
  workflow_dispatch:

jobs:
    
  task-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    inputs:
      issue:
        required: true

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ inputs.issue  }}
        transition: "In Progress"
