name: Change status

on: 
  workflow_call:  
    inputs:
      issue:   
        required: true
        type: string
        

jobs:
    
  task-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
        
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: "https://im486dx.atlassian.net"
        JIRA_USER_EMAIL: "im486dx@gmail.com"
        JIRA_API_TOKEN: "nlLbI2znqb5LYyyzj8In1110"


    - name: Get issue status
      id: get_status
      uses: ./.github/actions/gajira-status
      with:
        issue: inputs.issue

    - name: Transition issue
      uses: atlassian/gajira-transition@master
      if: ${{ steps.get_status.outputs.result == 'To Do' }}
      with:
        issue: ${{ inputs.issue }}
        transition: "In Progress"
