name: Change status

on: 
  workflow_dispatch:

jobs:
    
  task-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
        
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}


    - name: Get issue status
      id: get_status
      uses: ./.github/actions/gajira-status
      with:
        issue: "IM-1"

    - name: Transition issue
      uses: atlassian/gajira-transition@master
      if: ${{ steps.get_status.outputs.result != 'To Do' }}
      with:
        issue: "IM-1"
        transition: "In Progress"
