name: Change status

on: 
  workflow_dispatch:

jobs:
    
  task-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest

    steps:

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}


    - name: Get issue status
      uses: https://github.com/pingwiner/gajira-status@main
      with:
        issue: "IM-1"

    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: "IM-1"
        transition: "In Progress"
